# Generated by Django 4.0.1 on 2022-01-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбомы', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterField(
            model_name='text',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.track'),
        ),
    ]
